trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps: 
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.StagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.StagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DockerCompose@0
  displayName: 'Docker Build'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub/ferranramirez'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      PAT=$(PAT)
      ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENVIRONMENT)
    action: 'Build services'
    includeLatestTag: true

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub/ferranramirez'
    dockerComposeFile: '**/docker-compose.yml'    
    dockerComposeFileArgs: |
      PAT=$(PAT)
      ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENVIRONMENT)
    projectName: 'cloud.canister.io:5000/ferranramirez/ngnotguiriapi'
    action: 'Run a Docker Compose command'
    nopIfNoDockerComposeFile: true

- task: Docker@2
  displayName: 'Push image to Canister registry'
  inputs:
    containerRegistry: 'cloud.canister.io:5000/ferranramirez/'
    repository: 'ngnotguiriapi'
    command: 'push'
    tags: 'latest'
    addPipelineData: false