trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)'
    targetFiles: '**/appsettings.*.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish docker-deploy.yml'
  inputs:
    PathtoPublish: 'docker-deploy.yml'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'd73bd4e5-9a0c-45fc-ae19-1c2a40bfc9ee'
- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*.UnitTest.csproj'
- task: Docker@2
  displayName: 'Docker Build'
  inputs:
    containerRegistry: 'GitLabRegistry/ferranramirez'
    repository: 'notguiri/$(projectName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.SourceBranchName)'
    arguments: '--build-arg PAT=$(PAT)'
    addPipelineData: false
- task: Docker@2
  displayName: 'Docker Push'
  inputs:
    containerRegistry: 'GitLabRegistry/ferranramirez'
    repository: 'notguiri/$(projectName)'
    command: 'push'
    tags: '$(Build.SourceBranchName)'
    addPipelineData: false