version: '3.7'

services:
  ngnotguiriapi:
    container_name: ngnotguiriapi
    build:
      context: .
      args: 
        - "PAT=${PAT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports: 
      - "8083:80"
    networks:
      - local

networks:
  local:
    external: true