version: '3.7'

services:
  notguiriapi:
    image: registry.gitlab.com/notguiri/notguiriapi:latest
    deploy:
      # replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports: 
      - "8083:80"
    networks:
      - backend

networks:
  backend:
    external: true